/* ============================================================
   SJ ENGINEERING — Assistant
   Works out of the box with zero setup: answers are matched
   against a local knowledge base built from your company
   profile. If you add a free Groq API key (see the ⚙ note in
   the chat panel), it upgrades to full natural-language answers
   generated by an LLM that is grounded in the same data.
   ============================================================ */

const STORE_KEY = "sje_chat_history";
const API_KEY_STORE = process.env.GROK_API_KEY || import.meta.env.GROK_API_KEY;


const API_URL = "https://api.groq.com/openai/v1/chat/completions";
const WHATSAPP_NUMBER = "923009239576";

// ---------------------------------------------------------------
// 1. Knowledge base — edit this to keep the assistant up to date
// ---------------------------------------------------------------
const KB = {
  company: {
    name: "SJ Engineering",
    tagline: "Promising reliability for now and tomorrow",
    about: "SJ Engineering delivers comprehensive mechanical, industrial, and construction solutions built on precision, safety, and technical craftsmanship, acting as a single-source engineering partner for complex and heavy-duty projects.",
    vision: "To set new standards of quality, safety, and innovation in mechanical engineering, industrial construction, and renewable energy.",
    mission: "To deliver robust, sustainable, and cost-effective turnkey solutions that drive industrial growth and empower clients' operational success.",
    leadership: "Justin Parvez (CEO / Director) and Moon Sebastian (Managing Director).",
    address: "Plot # LS-05, ST # 1/3, Sector 21, Korangi Industrial Area, Karachi-74900, Pakistan.",
    phones: ["+92 300 9239 576", "+92 300 9239 476"],
    email: "sjengineeringsolution07@gmail.com"
  },
  services: [
    { key:"fabrication", name:"Fabrication & Erection", body:"Structural steel fabrication, industrial piping & spooling, site and machinery erection, tanks and custom metalwork — with certified SMAW/GTAW welding, NDT testing, and laser-aligned precision." },
    { key:"paints", name:"Sandblasting & Industrial Paints", body:"Abrasive sandblasting and grid blasting, epoxy/polyurethane/heat-resistant/anti-corrosive coating systems, tank & vessel lining, and structural steel painting." },
    { key:"ducting", name:"Ducting & Insulation Services", body:"HVAC ducting fabrication and installation in GI, SS and pre-insulated materials, thermal & acoustic insulation, plus duct sealing, leak testing and airflow balancing." },
    { key:"mechanical", name:"Mechanical Engineering", body:"Plant maintenance & overhauling, equipment installation, HVAC & industrial ducting, and piping & flow solutions — focused on minimizing downtime and precision execution." },
    { key:"fire", name:"Fire Fighting & Safety System", body:"Turnkey fire hydrant & sprinkler systems and fire pump station setup (electric, diesel standby, jockey pumps), fully compliant with local codes and NFPA standards." },
    { key:"boiler", name:"Boiler Maintenance & Installation", body:"Boiler installation & erection, piping & auxiliary integration, overhauling & refurbishment, plus preventive and emergency maintenance including PSV testing." },
    { key:"solar", name:"Solar Power Solutions", body:"Turnkey EPC for on-grid, off-grid and hybrid solar systems, structural mounting design, inverter & electrical integration, and ongoing system testing & maintenance." },
    { key:"construction", name:"Industrial Construction", body:"Turnkey factory & warehouse construction, heavy machinery foundations, structural concrete & civil works, and site development & infrastructure." }
  ],
  tools: ["Sheet Rolling Machine","Welding Plant","Grinders (4\" & 9\")","Auto & Gas Cutters","Hilti & Radial Drill Machines","Oxygen/Faun Gas Cylinders","CO2 & Argon Welding","Milling & Shaper Machines","Air Compressor","Mobile Hydraulic Crane","Excavator","Soil Compactor","Jack Hammer","Lathe Machine","Power Press","Punching & Banding Machines","Cladding & Ducting Machines","Magnetic Drill Machine","Laser Level","HDPE Welding Machine","Dumper/Loader Trucks","Tractor","Total Station"],
  why: [
    "Single-source engineering, mechanical, and construction solutions under one roof.",
    "Certified welding standards, advanced NDT testing, and precise field alignments.",
    "International HSE protocols and detailed site risk assessments for a zero-harm environment.",
    "Streamlined project management and proactive site planning to minimize downtime and cost."
  ]
};

function waLink(text){
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;
}

// ---------------------------------------------------------------
// 2. Local answer engine (keyword scoring — no dependencies)
// ---------------------------------------------------------------
function localAnswer(query){
  const q = query.toLowerCase();

  const contactWords = ["contact","phone","number","call","email","address","location","whatsapp","reach"];
  if(contactWords.some(w=>q.includes(w))){
    return `You can reach ${KB.company.name} at ${KB.company.phones.join(" or ")}, or by email at ${KB.company.email}.<br>Workshop: ${KB.company.address}<br><a href="${waLink('Hi SJ Engineering, I would like to get in touch.')}" target="_blank" rel="noopener">Message us on WhatsApp →</a>`;
  }

  if(/vision/.test(q)) return KB.company.vision;
  if(/mission/.test(q)) return KB.company.mission;
  if(/ceo|director|leadership|who runs|founder/.test(q)) return `${KB.company.name} is led by ${KB.company.leadership}`;
  if(/about|who are you|what is sj|company/.test(q) && !/service|product/.test(q)) return KB.company.about;
  if(/tool|equipment|machine/.test(q)) return `Our workshop runs a full fleet of fabrication and site equipment, including ${KB.tools.slice(0,8).join(", ")}, and more — ${KB.tools.length} machine types in total.`;
  if(/why (choose|you|sj)|advantage|different/.test(q)) return KB.why.map(w=>`• ${w}`).join("<br>");

  // service matching — score each service by keyword overlap
  let best = null, bestScore = 0;
  KB.services.forEach(s=>{
    const hay = (s.name + " " + s.body).toLowerCase();
    let score = 0;
    q.split(/\W+/).filter(Boolean).forEach(word=>{
      if(word.length > 2 && hay.includes(word)) score++;
    });
    if(score > bestScore){ bestScore = score; best = s; }
  });
  if(best && bestScore > 0){
    return `<strong>${best.name}</strong><br>${best.body}<br><a href="${waLink('Hi, I would like a quote for ' + best.name + '.')}" target="_blank" rel="noopener">Ask for a quote on WhatsApp →</a>`;
  }

  if(/service|product|offer|what do you do/.test(q)){
    return `We work across eight core lines: ${KB.services.map(s=>s.name).join(", ")}. Ask me about any one of these for details.`;
  }

  return null; // signal: no confident local match
}

function fallbackAnswer(){
  return `I don't have a confident answer for that from our service data yet. Our team can help directly — <a href="${waLink('Hi SJ Engineering, I have a question:')}" target="_blank" rel="noopener">chat with us on WhatsApp →</a>`;
}

// ---------------------------------------------------------------
// 3. Optional LLM upgrade (Groq) — grounded in the same KB
// ---------------------------------------------------------------
function systemPrompt(){
  return `You are the official assistant for ${KB.company.name} ("${KB.company.tagline}"). ` +
    `Only answer using the facts given here — never invent services, prices, or specs. ` +
    `About: ${KB.company.about} Vision: ${KB.company.vision} Mission: ${KB.company.mission} ` +
    `Leadership: ${KB.company.leadership} Contact: ${KB.company.phones.join(" / ")}, ${KB.company.email}. ` +
    `Workshop address: ${KB.company.address}. ` +
    `Services: ${KB.services.map(s=>`${s.name} — ${s.body}`).join(" | ")} ` +
    `Tools & equipment on hand: ${KB.tools.join(", ")}. ` +
    `Why choose us: ${KB.why.join(" ")} ` +
    `Keep replies short (2-4 sentences), practical, and steer people toward WhatsApp (${KB.company.phones[0]}) for quotes or site visits. Use a couple of relevant emojis sparingly.`;
}

async function llmAnswer(history, apiKey){
  const res = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", "Authorization": "Bearer " + apiKey },
    body: JSON.stringify({
      model: "openai/gpt-oss-20b",
      temperature: 0.4,
      messages: [{ role:"system", content: systemPrompt() }, ...history.slice(-8)]
    })
  });
  if(!res.ok){
    const body = await res.text().catch(()=> "");
    throw new Error(`API ${res.status}: ${body || res.statusText}`);
  }
  const data = await res.json();
  return data.choices?.[0]?.message?.content || null;
}

// ---------------------------------------------------------------
// 4. UI wiring
// ---------------------------------------------------------------
export function initChatbot(){
  const launcher = document.getElementById("chat-launcher");
  const panel = document.getElementById("chat-panel");
  const closeBtn = document.getElementById("chat-close");
  const body = document.getElementById("chat-body");
  const form = document.getElementById("chat-form");
  const input = document.getElementById("chat-input");
  const chipsWrap = document.getElementById("chat-chips");
  const keyLink = document.getElementById("chat-key-link");

  if(!launcher || !panel) return;

  let history = load();
  let awaitingKey = false;

  function load(){
    try{ return JSON.parse(sessionStorage.getItem(STORE_KEY)) || []; }
    catch{ return []; }
  }
  function save(){ sessionStorage.setItem(STORE_KEY, JSON.stringify(history)); }

  function addMessage(role, html){
    const el = document.createElement("div");
    el.className = `msg ${role === "user" ? "user" : "bot"}`;
    el.innerHTML = html;
    body.appendChild(el);
    body.scrollTop = body.scrollHeight;
    return el;
  }

  function renderHistory(){
    body.innerHTML = "";
    if(history.length === 0){
      addMessage("bot", `👋 Hi, I'm the ${KB.company.name} assistant. Ask me about our services, tools, or how to get a quote.`);
      return;
    }
    history.forEach(m => addMessage(m.role === "user" ? "user" : "bot", linkify(m.content)));
  }

  function linkify(text){
    return text.replace(/\n/g, "<br>");
  }

  const CHIPS = ["Fabrication & Erection", "Boiler Maintenance", "Solar Power Solutions", "Get a quote"];
  chipsWrap.innerHTML = CHIPS.map(c => `<button class="chip" type="button">${c}</button>`).join("");
  chipsWrap.querySelectorAll(".chip").forEach(chip=>{
    chip.addEventListener("click", ()=>{
      input.value = chip.textContent === "Get a quote" ? "How do I get a quote?" : `Tell me about ${chip.textContent}`;
      form.requestSubmit();
    });
  });

  launcher.addEventListener("click", ()=>{
    panel.classList.add("open");
    if(history.length === 0) renderHistory();
    input.focus();
  });
  closeBtn.addEventListener("click", ()=> panel.classList.remove("open"));

  keyLink.addEventListener("click", (e)=>{
    e.preventDefault();
    const current = localStorage.getItem(API_KEY_STORE) || "";
    const key = prompt("Paste a free Groq API key to upgrade to full AI answers (get one at console.groq.com). Leave blank to keep using the built-in knowledge base.", current);
    if(key !== null){
      if(key.trim()) localStorage.setItem(API_KEY_STORE, key.trim());
      else localStorage.removeItem(API_KEY_STORE);
      keyLink.textContent = key.trim() ? "AI mode: on ⚡ (click to change)" : "Enable full AI mode ⚡ (optional)";
    }
  });
  const savedKey = localStorage.getItem(API_KEY_STORE);
  keyLink.textContent = savedKey ? "AI mode: on ⚡ (click to change)" : "Enable full AI mode ⚡ (optional)";

  form.addEventListener("submit", async (e)=>{
    e.preventDefault();
    const text = input.value.trim();
    if(!text) return;
    input.value = "";

    history.push({ role:"user", content:text });
    addMessage("user", linkify(text));
    save();

    const typingEl = addMessage("bot", `<span class="typing"><span></span><span></span><span></span></span>`);

    let replyHTML;
    // const apiKey = localStorage.getItem(API_KEY_STORE);
    const apiKey=process.env.GROK_API_KEY || import.meta.env.GROK_API_KEY
    if(apiKey){
      try{
        const reply = await llmAnswer(history, apiKey);
        replyHTML = linkify(reply || fallbackAnswer());
      }catch(err){
        replyHTML = localAnswer(text) || `⚠️ Couldn't reach the AI service (${err.message}). ` + fallbackAnswer();
      }
    }else{
      replyHTML = localAnswer(text) || fallbackAnswer();
    }

    typingEl.innerHTML = replyHTML;
    history.push({ role:"assistant", content: replyHTML });
    save();
    body.scrollTop = body.scrollHeight;
  });

  renderHistory();
}
